# Generated by Django 5.0.2 on 2024-02-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_app', '0002_parents_teachers_alter_students_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=255)),
                ('author', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
